### PR TITLE
Fill Triangle on Bitmap Example Updates

### PR DESCRIPTION
**Pull request by EthanRin**
# Overview

Added usage example for fill_ellipse including C# OOP and Python

## SplashKit Function: fill_triangle_on_bitmap

- [x] C# Code (Object-Oriented Programming)
- [x] Python Code
- [x] Update naming for Top Level Code

## Checklist

- [x] Clear Demonstration of the function
- [x] Code uses Splashkit Function
- [x] Tested on Chrome and it's fully functioning

## Folders and Files Added/Modified

- Added:
  - [x] fill_triangle_on_bitmap/fill_triangle_on_bitmap-1-simple.py
  - [x] fill_triangle_on_bitmap/fill_triangle_on_bitmap-1-simple-oop.cs
- Modified:
  - [x] fill_triangle_on_bitmap/fill_triangle_on_bitmap-1-simple-top-level.cs

### CODE REVIEW

**Review by ctrlvish — CHANGES_REQUESTED** [review]
Hi Ethan, I've tested your changes on my Chrome and Firefox and it seems good! 

There is one mistake with the function call on line 33 of your python implementation though, the function should be called free_all_bitmaps (missing s). Renaming this function in my test environment got rid of the squiggly line below it. Hope this feedback helps!

**Comment by ctrlvish** [comment]
Hi Ethan, I noticed that the C++ version of the code includes a comment with a link above the load_bitmap functions, but this is missing in the other code versions (C#, Python, etc.). To ensure consistency across all files, could you please add the same link comment above the equivalent sections in the other languages? Thank you

**Comment by EthanRin** [comment]
Hello @ctrlvish I've updated the changes according to your request

**Review by huyhuynh2319 — APPROVED** [review]
I've reviewed the usage examples. Everything ran without issue.

### **Checks**

- [x]  All required files are present.
- [x]  Title and explanation (.txt)
- [x]  C++ code
- [x]  C# code (top-level statements)
- [x]  C# code (Object-Oriented Programming)
- [x]  Python code

### **Tests done**

- [x]  C++ code ran correctly.
- [x]  C# top level code ran correctly.
- [x]  C# OOP code ran correctly.
- [x]  Python code ran correctly.

**Comment by ctrlvish** [comment]
I've reviewed this PR, everything looks good!
- [x] All required files are present.
  - [x] Title and explanation (.txt)
  - [x] C++ code
  - [x] C# code (top-level statements)
  - [x] C# code (Object-Oriented Programming)
  - [x] Python code
- [x] Code correctly uses Splashkit functions.
- [x] Code clearly demonstrates the function.
- [x] All versions maintain the same structure and comments.
- [x] C++ code ran correctly.
- [x] C# top level code ran correctly.
- [x] C# OOP code ran correctly.
- [x] Python code ran correctly.

**Review by ctrlvish — APPROVED** [review]
I've reviewed this PR, everything looks good!

- [x] All required files are present.
  - [x] Title and explanation (.txt)
  - [x] C++ code
  - [x] C# code (top-level statements)
  - [x] C# code (Object-Oriented Programming)
  - [x] Python code
- [x] Code correctly uses Splashkit functions.
- [x] Code clearly demonstrates the function.
- [x] All versions maintain the same structure and comments.
- [x] C++ code ran correctly.
- [x] C# top level code ran correctly.
- [x] C# OOP code ran correctly.
- [x] Python code ran correctly.

**Review by omckeon — APPROVED** [review]
I've updated the C# OO code slightly - the commented line above the OO style could be a good way to improve the highlighting and show both formats that can be used.
You could share this idea in the group chat for helping those that have done the "On Bitmap" or "On Window" functions.

**Pull request merged**
