### PR TITLE
Tutorial Review of getting started with servers guide

### PR DESCRIPTION
**Pull request by breezy-codes**
A tutorial review was conducted on the Getting Started with Servers guide page. The program code was tested for each language, issues were identified in the C++ version of code where in step 3 and in step 4 it used `web_server` instead of `start_web_server` which has been now fixed.

## Changes:

- Updated the code errors for C++ in step 3 and step 4 

## Checks done:

- [X] Tested in latest Chrome
- [X] Tested in latest Firefox
- [X] npm run build
- [X] npm run preview

## Code Checks:

- [X] Checked C#
- [X] Checked C++
- [X] Checked Python

# Code output results:

### Step 2
1step2-python

### Step 3
2step3-python

### Step 4
3step4-python

### Step 2
6step2-cpp

### Step 3 error
7step3-4-error-cpp

### Step 3 fix
8step3-fixed-cpp

### Step 4
9step4-fixed-cpp

### Step 2
12-step2-csharp

### Step 3
13step3-csharp

### Step 4
14step4-csharp

### CODE REVIEW

**Review by oliverexell-bruce — CHANGES_REQUESTED** [review]
A few things to check with this.

1. Step 2 for Python has an error. You just need to add `_with_default_port` to line 6 like is in steps 3 and 4. 
2. Line 48 you added a section saying to add this code into the resources folder, however it is my understanding that this is the program code and therefore should be in the main program folder (replacing the default code in the 'program.py' file).  
3. In step 4 of the C# and Python code the webpage isn't displayed. My guess is that the index.html file wasn't created so a blank page was displayed like in step 2. Code looks fine but maybe best to double check.

Other than that, looks good.

**Review by oliverexell-bruce — APPROVED** [review]
## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (update or new)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration.

- [X] Tested in latest Chrome
- [X] Tested in latest Firefox
- [X] npm run build
- [X] npm run preview


## Folders and Files Added/Modified

Please list the folders and files added/modified with this pull request.

- Added:
  - [ ] N/A
- Modified:
  - [X] src/content/docs/guides/networking/0-getting-started-with-servers.mdx


Looks great, good work

**Review by NidhishaPahade — APPROVED** [review]
Everything looks good. Great work !!

**Review by omckeon — APPROVED** [review]
Great catches in the code!

**Pull request merged**
