### PR TITLE
Updated Broken Links

### PR DESCRIPTION
**Pull request by ShaunR1991**
Ran the link checker tool and found a number of broken links which have now been fixed:

URL resource%20bundles
Name Resource Bundles
Parent URL https://splashkit.io/api/, line 151, col 9835
Real URL https://splashkit.io/api/resource%20bundles

URL /images/installation/windows-msys2/mingw64-pin-to-taskbar.png
Name Image showing MSYS2 MINGW64 App pinning to taskbar
Parent URL https://splashkit.io/installation/windows-msys2/step-1/, line 169, col 9
Real URL https://splashkit.io/images/installation/windows-msys2/mingw64-pin-to-taskbar.png

URL /troubleshoot/Windows/windows/
Name Previous Mac FAQs
Parent URL https://splashkit.io/troubleshoot/windows/windows/, line 160, col 242
Real URL https://splashkit.io/troubleshoot/Windows/windows/

URL /troubleshoot/Linux/linux/
Name Next Windows FAQs
Parent URL https://splashkit.io/troubleshoot/linux/linux/, line 151, col 883
Real URL https://splashkit.io/troubleshoot/Linux/linux/

URL /troubleshoot/MacOS/mac/
Name Next Windows FAQs
Parent URL https://splashkit.io/troubleshoot/macos/mac/, line 161, col 806
Real URL https://splashkit.io/troubleshoot/MacOS/mac/

URL /troubleshoot/Windows-WSL/WSL/
Name Next Windows FAQs
Parent URL https://splashkit.io/troubleshoot/windows-wsl/wsl/, line 154, col 835
Real URL https://splashkit.io/troubleshoot/Windows-WSL/WSL/

URL /gifs/windows/install-gpp-msys.gif' Name       install-gpp-msys'
Parent URL https://splashkit.io/installation/windows-msys2/languages/gcc-not-in-use/, line 158, col 4
Real URL https://splashkit.io/gifs/windows/install-gpp-msys.gif

URL /gifs/windows/demo-compiler.gif' Name       demo-compiler'
Parent URL https://splashkit.io/installation/windows-msys2/languages/gcc-not-in-use/, line 162, col 4
Real URL https://splashkit.io/gifs/windows/demo-compiler.gif

URL /gifs/windows/extensions.gif' Name       extensions'
Parent URL https://splashkit.io/installation/windows-msys2/languages/gcc-not-in-use/, line 174, col 4
Real URL https://splashkit.io/gifs/windows/extensions.gif

### CODE REVIEW

**Review by ShaunR1991 — COMMENTED** [review]
Updated link.

**Comment by ShaunR1991** [comment]
Ran the link checker tool and found a number of broken links which have now been fixed:

URL        `resource%20bundles'
Name       `Resource Bundles'
Parent URL https://splashkit.io/api/, line 151, col 9835
Real URL   https://splashkit.io/api/resource%20bundles

URL        `/images/installation/windows-msys2/mingw64-pin-to-taskbar.png'
Name       `Image showing MSYS2 MINGW64 App pinning to taskbar'
Parent URL https://splashkit.io/installation/windows-msys2/step-1/, line 169, col 9
Real URL   https://splashkit.io/images/installation/windows-msys2/mingw64-pin-to-taskbar.png

URL        `/troubleshoot/Windows/windows/'
Name       `Previous  Mac FAQs'
Parent URL https://splashkit.io/troubleshoot/windows/windows/, line 160, col 242
Real URL   https://splashkit.io/troubleshoot/Windows/windows/

URL        `/troubleshoot/Linux/linux/'
Name       `Next  Windows FAQs'
Parent URL https://splashkit.io/troubleshoot/linux/linux/, line 151, col 883
Real URL   https://splashkit.io/troubleshoot/Linux/linux/

URL        `/troubleshoot/MacOS/mac/'
Name       `Next  Windows FAQs'
Parent URL https://splashkit.io/troubleshoot/macos/mac/, line 161, col 806
Real URL   https://splashkit.io/troubleshoot/MacOS/mac/

URL        `/troubleshoot/Windows-WSL/WSL/'
Name       `Next  Windows FAQs'
Parent URL https://splashkit.io/troubleshoot/windows-wsl/wsl/, line 154, col 835
Real URL   https://splashkit.io/troubleshoot/Windows-WSL/WSL/

URL        `/gifs/windows/install-gpp-msys.gif'
Name       `install-gpp-msys'
Parent URL https://splashkit.io/installation/windows-msys2/languages/gcc-not-in-use/, line 158, col 4
Real URL   https://splashkit.io/gifs/windows/install-gpp-msys.gif

URL        `/gifs/windows/demo-compiler.gif'
Name       `demo-compiler'
Parent URL https://splashkit.io/installation/windows-msys2/languages/gcc-not-in-use/, line 162, col 4
Real URL   https://splashkit.io/gifs/windows/demo-compiler.gif

URL        `/gifs/windows/extensions.gif'
Name       `extensions'
Parent URL https://splashkit.io/installation/windows-msys2/languages/gcc-not-in-use/, line 174, col 4
Real URL   https://splashkit.io/gifs/windows/extensions.gif

**Review by Liquidscroll — CHANGES_REQUESTED** [review]
The actual changes to the content look good!

The issue you're having with Resource Bundles.mdx is because this is generated through components.cjs, so you rename it but the github actions generate it and then there's a duplicate.

If I'm understanding the code correctly, you should be able to solve this by replacing the space in the name with a dash when the file is written, so we go from `${name}` to `${name.replace(/ /g, "-")}` , see below for the exact fix:

image

This should keep the website displaying "Resource Bundles" while making the actual file "Resource-Bundles.mdx"

**Comment by ShaunR1991** [comment]
> The actual changes to the content look good!
> 
> The issue you're having with Resource Bundles.mdx is because this is generated through components.cjs, so you rename it but the github actions generate it and then there's a duplicate.
> 
> If I'm understanding the code correctly, you should be able to solve this by replacing the space in the name with a dash when the file is written, so we go from `${name}` to `${name.replace(/ /g, "-")}` , see below for the exact fix:
> 
> image
> 
> This should keep the website displaying "Resource Bundles" while making the actual file "Resource-Bundles.mdx"

Thanks for the feedback - i've finally gotten around to fixing this. It should work correctly now :)

**Review by Liquidscroll — APPROVED** [review]
Thanks for the changes!

Looks good to me!

**Pull request merged**
