### PR TITLE
Splashkit camera - C#  Language update

### PR DESCRIPTION
**Pull request by s223126445**
## Description:

Description
This tutorial has been updated to include object-oriented programming (OOP) concepts in the C# language examples. The changes improve code structure and reusability, making it easier to understand and maintain. The update addresses the need for more structured and scalable code as part of the SplashKit tutorial improvements.

## Type Of Change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (update or new)

## How Has This Been Tested?:

- [x] Tested in latest Chrome
- [x]  Tested in latest Firefox
- [x] npm run build
- [x]  npm run preview

### If involving code
 - [x] My code follows the style guidelines of this project
 - [x] I have performed a self-review of my own code
- [x]  I have commented my code in hard-to-understand areas
- [x]  I have made corresponding changes to the documentation
- [x]  My changes generate no new warnings

### If modified config files

- [x] I have checked the following files for changes:
  - [x] package.json
  - [x] astro.config.mjs
  - [x] netlify.toml
  - [x] docker-compose.yml
  - [x] custom.css

## Folders and Files Added/Modified
- Modified:
  - [x] folder/file

## Additional Notes
"The updated C# tutorial now includes object-oriented programming concepts like organizing code into classes and using inheritance. This makes the examples easier to understand and follow good coding practices."

## Screenshot Of Code:
Camera_test

### CODE REVIEW

**Comment by Srainyyyy** [comment]
C# OOP code works fine, and the results are consistent with other code
image

**Review by Srainyyyy — APPROVED** [review]
C# OOP code works fine, and the results are consistent with other code

**Review by breezy-codes — CHANGES_REQUESTED** [review]
Within the other code blocks on this tutorial there are comments, for example in the top level version there is:
```
    // Test if the player is outside the area and move the camera
    // the player will appear to stay still and everything else
    // will appear to move :)
```
Please add the similar comments into the OOP version so it matches in with the other ones on this guide.

**Comment by breezy-codes** [comment]
The program code runs correctly for me, I compared it with the top level version to ensure they worked the same.
Please update to have the same type of code comments as the other code types on this.

**Comment by s223126445** [comment]
I have made the requested changes changes please check.

**Comment by omckeon** [comment]
I've now fixed up the issues with the OOP code not following the same format as the other code blocks, as well as other issues.

This can now be merged, but any approving reviews won't be counted, and this will only count as a partial contribution to this task.

**Pull request merged**
