### PR TITLE
Complete Overhaul of the Installation and Troubleshooting Sections

### PR DESCRIPTION
**Pull request by breezy-codes**
# Description

This pull request presents a comprehensive update to the installation and troubleshooting pages for SplashKit. Key changes include adding different distributions across Linux installation guides, expanded troubleshooting sections for Linux, and improved page descriptions and formatting throughout. Visual studio code extension sections were all updated to include screenshots of the extensions within vscode, as well as adding in the WSL extension into the WSL install. Python install was added to each language tools page, as well as the vscode extension pages.

### Linux Install Pages
- **Expanded Distribution Coverage:** Updated all Linux installation guides to include commands for popular distributions: Ubuntu, Arch (using Pacman and yay), Fedora, and Alpine. Each guide is tailored with specific commands and configurations to streamline setup for users across these distributions.
- **Visual Studio Code Installation Guide:** Updated the Linux Visual Studio Code installation instructions to reflect distribution-specific steps, as the process can vary significantly between Linux distros.
- **Language-Specific Tooling:** Expanded the language tools section to show installation commands for each distro, alongside instructions for ensuring `bash` or `zsh` profiles are updated. This includes guidance on handling cases where these profiles don't automatically integrate required configurations.
- **Python Installation Guide:** Added detailed Python installation instructions for each Linux distribution, covering multiple installation methods and best practices.

### WSL, Windows and Mac Update
- **Python Installation:** Enhanced the WSL, Windows and Mac sections of the language tools page to include Python installation steps, making it easier for users to set up essential language support across these environments.

### Visual Studio Code Pages
- **Improved Visual Studio Code Installation Instructions:** Revised all "Install Visual Studio Code" pages under the "Install Extensions" section to provide:
  - **Direct Links and Command Line Options:** Added direct links to Visual Studio Code extensions, plus command-line options for those who prefer terminal-based setups.
  - **Visual Enhancements:** Included a screenshot of the extensions section within VS Code, offering users a clearer understanding of expected configurations and available options.
  - **Added Python:** Included the python extension pack to all pages.

### Home Page / Troubleshoot Overview Page
- **Home Page Update:** Updated the home page for the "FAQ" section so it now also mentions there is troubleshooting docs for WSL and Linux
- **Troubleshoot Overview:** Updated the overview page, mentioned there is a Splashkit update page and also included links to Linux and WSL.

### Update Splashkit
- **Splashkit Update Page:** I noticed there was an `update skm` command when updating the skm repo README. So I created a page to show how to update splashkit.

### General Install / Troubleshooting Updates
- **Enhanced Page Descriptions:** Updated the front matter of each installation page to include a succinct, informative description.
- **Step-by-Step Structure:** Introduced clear, numbered steps to each installation page, making it easier to follow. Using the astro `steps` component.
- **Button-Based Navigation:** Replaced text links with buttons for a cleaner, more modern navigation experience.

### Organisation and Improvements
- **Streamlined Navigation:** Removed redundant "list" folders under each troubleshooting section, making it easier for users to locate specific troubleshooting topics.
- **Clearer Step Instructions:** Updated each guide to have steps using the astro component, in addition more information was added for creating a clear flow through the steps.
- **Updated Page Descriptions:** Revised front matter descriptions to provide a clear summary of each troubleshooting page’s purpose.

### Linux Troubleshooting
- **New Page for Installation Errors:** Added a troubleshooting page for handling `skm global install` errors, often caused by issues with `bash` or `zsh` configurations. This page provides steps for diagnosing and fixing the problem, ensuring smoother Linux installs.
- **Library Path Issue Resolution:** Created a dedicated page for resolving errors like `libsplashkit.so` not found, which occur when library paths are accidentally removed from `bash` or `zsh` profiles. This guide offers detailed steps for restoring necessary library paths.

## Type of Change

_Please delete options that are not relevant._

- [X] New feature (non-breaking change which adds functionality)
- [X] Documentation (update or new content)

## How Has This Been Tested?

The updated pages were reviewed across various browsers to ensure proper formatting and functionality, including testing all links. Verification steps included running `npm run build` and manual review to confirm that all Linux installation steps function correctly for each distribution covered.

## Testing Checklist

- [X] Tested in latest Chrome
- [X] Tested in latest Firefox
- [X] `npm run build`
- [X] `npm run preview`

## Folders and Files Added/Modified

This update affects the entire installation and troubleshooting section. Two new troubleshooting pages were added: `linux-issue-1` (installation issues) and `linux-issue-2` (library path issues).
Created updating-splashkit file

### CODE REVIEW

**Comment by ctrlvish** [comment]
I have reviewed the MacOS installation pages on my end. Everything seems to run smoothly and the steps are clear. I have a suggestion to add compilation steps for the code languages (like using -l splashkit when compiling cpp code with g++) or explaining what the resources folder can do. But maybe this can be implemented in a future PR for this page. Or in a separate tutorials page if needed :)

**Comment by breezy-codes** [comment]
@ctrlvish there is actually an existing page that goes over the commands for compilation of each language - 
https://splashkit.io/guides/using-splashkit/0-overview/

If you think that page would benefit from some updates please let me know and I can add it into this PR

**Comment by ctrlvish** [comment]
> @ctrlvish there is actually an existing page that goes over the commands for compilation of each language - https://splashkit.io/guides/using-splashkit/0-overview/
> 
> If you think that page would benefit from some updates please let me know and I can add it into this PR

It looks good!

image

A suggestion is that we can simplify this command to just be `python3 program.py`.

**Review by SimonRhook — CHANGES_REQUESTED** [review]
I've reviewed the windows install, Ubuntu and Fedora installation guides and using the guides was able to successfully install SplashKit on fresh virtual machines and run a a basic hello world program. 

Ubuntu guide is great, very easy to follow and I didn't run into any issues

I did find a broken button in installation/linux/step-4/ . The button labelled .NET Download Page does not work and contains a broken link.

I do have 2 recommended changes, one for windows and one for fedora.

### Windows
During the python install there is a small wording change I recommend. Currently the guide says 
image

where the python install wizard says 

image. 

This is a very minor change but I think someone with very limited computer knowledge may get confused.

### Fedora
Currently on the guide the method to install VS Code is different from what is required. The guide says to download a .rpm file and install it using sudo dnf install code-1.*.rpm whereas the link to the VScode website has you install it straight from a repository 
image
these steps are still very simple to follow but they are different from the guide.

### Edit: 
I have now tested the Arch install using Manjaro distro, I have found that the first upgrade command `sudo pacman -Syu` repository for upgrading the libjxl dependency for SDL2_image which was causing an install error for SplashKit. I found a similar issue on the Manjaro forum which resolved it with the command `pamac update --no-aur` which linked to newer update repos. So perhaps this can be added to troubleshooting steps for anyone else that may encounter this?

The other recommendation I have for the arch install is when stepping through the installation for VS Code, a note stating that the open source install (Code - OSS) will not give access to the Microsoft extension packages that are highly recommended in the next step. So perhaps state if Microsoft Dev tools are wanted to install the proprietary  version of VS code with the yay command.

**Comment by breezy-codes** [comment]
Thank you for the feedback.
I've updated the wording in the Windows install.

Updated the linux install for vs code showing ubuntu way, then fedora was as they're now different.
Also added a note that code-oss doesnt let you do command line for extensions, also swapped to have the proper vscode at the top as a recommended one.

I also added in a page about the arch for troubleshooting, Olivia found the issue was an error with the mv command, however as you had an issued with a corrupted repo I thought that is a good idea to add in that troubleshooting page because these things can break on linux.

**Review by SimonRhook — APPROVED** [review]
## General Information

This PR does a very good job of updated the install guides for various operating systems. It is easy to follow, the language is clear and the steps are all beginner friendly. I Approve this PR

- [x] Type of Change: Clearly indicate the type of change (choose one):
  - [ ] Bug fix
  - [ ] New feature
  - [ ] Breaking change
  - [x] Documentation update

## Testing
I've tested this bu individually stepping through the guide on Fresh virtual machines on Windows, Ubuntu, Arch(manjaro), and Fedora. In all cases I imported the commands directly from the guide which lead to seamless setup. 

For the VS code I also tested the command line install and the extension page within VS code and found the language to be clear and easy to follow.

- [x] Test Coverage: Are unit tests provided for new or modified code?
- [x] Test Results: Have all tests passed successfully?

## Documentation

- [x] Documentation: Is the inline and external documentation updated and clear?

## Pull Request Details

- [x] PR Description: Is the problem being solved clearly described?
- [x] Checklist Completion: Have all relevant checklist items been reviewed and completed?

**Pull request closed without merging**
