### PR TITLE
New usage example for Draw quad on window

### PR DESCRIPTION
**Pull request by SimonRhook**
# Overview

Added in usage example for draw_quad_on_window including C\# OOP and Top level, Python and C++

# Files Included

Splashkit Function: `draw_quad_on_window`
- [x] Title and explanation (.txt)
- [x] C++ code
- [x] C# code (top-level statements)
- [x] C# code (Object-Oriented Programming)
- [x] Python code
- [x] Screenshot

# Usage Example Checks

- [x] Simple, clear demonstration of the function
- [x] Code uses Splashkit functions
- [x] Tested in Chrome and Firefox

### CODE REVIEW

**Review by Jinx-means-jinx — COMMENTED** [review]
Check the code for oop and running with no error
image

Check the code for top level and running with no error
image

Check the code for C++ and running with no error
image

Check the code for python and running with no error
image

**Review by Jinx-means-jinx — APPROVED** [review]
Code should use the same format
image
Delete she extra space there
Quad q1 = QuadFrom(400,200,300,300,300,0,200,200);   
Quad q2 = QuadFrom(400,210,310,300,600,300,400,390);
Quad q3 = QuadFrom(200,400,300,300,300,600,400,400);
Quad q4 = QuadFrom(200,390,290,300,0,300,200,210);

**Review by huyhuynh2319 — APPROVED** [review]
I reviewed this pull request. Everything looks to be in order, the programs work well 

- [x] C++ code ran correctly.
- [x] C# top level code ran correctly.
- [x] C# OOP code ran correctly.
- [x] Python code ran correctly.

**Comment by omckeon** [comment]
See my review comments on the "Create usage example for draw_line_on_window" PR [here](https://github.com/thoth-tech/splashkit.io-starlight/pull/235#pullrequestreview-2472288685) and make relevant updates.

**Review by omckeon — APPROVED** [review]

**Pull request merged**
