### PR TITLE
Added usage example for fill_quad_on_window

### PR DESCRIPTION
**Pull request by SimonRhook**
# Overview

Added usage example for fill_quad_on_window including C\# OOP and Top Level, C++ and Python 

# Files Included

Splashkit Function: `fill_quad_on_window`
- [x] Title and explanation (.txt)
- [x] C++ code
- [x] C# code (top-level statements)
- [x] C# code (Object-Oriented Programming)
- [x] Python code
- [x] Screenshot

# Usage Example Checks

- [x] Simple, clear demonstration of the function
- [x] Code uses Splashkit functions
- [x] Tested in Chrome and Firefox

### CODE REVIEW

**Review by Jinx-means-jinx — COMMENTED** [review]
Check the code for oop and running with no error
image

Check the code for top level and running with no error
image

Check the code for C++ and running with no error
image

Check the code for python and running with no error
image

**Review by Jinx-means-jinx — APPROVED** [review]
Code should use the same format
image
Delete she extra space there
Quad q1 = QuadFrom(400,200,300,300,300,0,200,200);   
Quad q2 = QuadFrom(400,210,310,300,600,300,400,390);
Quad q3 = QuadFrom(200,400,300,300,300,600,400,400);
Quad q4 = QuadFrom(200,390,290,300,0,300,200,210);

**Review by breezy-codes — CHANGES_REQUESTED** [review]
This program is VERY cool! I love the use of having the two windows there and how the pattern goes across!
I have similar request here as I did on some others, can you remove the double line spacing and have it just be single line?

**Review by breezy-codes — APPROVED** [review]
I've reviewed this PR, all code files run correctly and are free of any errors. Code comments are consistent and so is the code.

I approve of this PR.


- [X] All required files are present.
  - [X] Title and explanation (.txt)
  - [X] C++ code
  - [X] C# code (top-level statements)
  - [X] C# code (Object-Oriented Programming)
  - [X] Python code
- [X] Code correctly uses Splashkit functions.
- [X] Code clearly demonstrates the function.
- [X] All versions maintain the same structure and comments.
- [X] C++ code ran correctly.
- [X] C# top level code ran correctly.
- [X] C# OOP code ran correctly.
- [X] Python code ran correctly.

**Comment by omckeon** [comment]
See my review comments on the "Create usage example for draw_line_on_window" PR [here](https://github.com/thoth-tech/splashkit.io-starlight/pull/235#pullrequestreview-2472288685) and make relevant updates.

**Pull request merged**
