### PR TITLE
Physics Tutorial Suite

### PR DESCRIPTION
**Pull request by ShaunR1991**
Created a new suite of 2D vectors tutorials under the Physics banner. 

These tutorials introduce the fundamental concepts of vectors and their applications. Users will learn how to define, visualise, and manipulate vectors using SplashKit's built-in functions. The tutorial covers essential vector operations such as calculating angle and magnitude, vector arithmetic, basic collisions and geometry. By the end, the user will have a greater understanding of vectors and how to use them to enhance their games.

### CODE REVIEW

**Review by The-0x — APPROVED** [review]
Good work on the tutorial, it is very informative. 
I followed it as the intended "as-you-go" style through the deploy preview, functionally all links and interactive parts of the tutorial work as intended. All code examples were tested and outputted the expected results (C++ & C#). Knowledge and explanations of the topics and their possible use cases were clearly shown and easy to follow. By the end of the tutorial a user would see the benefit and have the knowledge to implement this into their own projects.
I feel as though adding code snippets for the functions in '_3-vector-geometry-angles_' , similar to that in the other topics, would be beneficial to the reader. As well as implementing C# code to '_4-collision-detection-using-vectors_'.

**Review by oliverexell-bruce — COMMENTED** [review]
The following lines should use relative links instead of hard coded links
- Introduction to vectors - Lines 24-25
- Vector magnitudes - Lines 24-26
- Vector arithmetic - Lines 24-26
- Collision detection using vectors - Lines 24-28

**Comment by ShaunR1991** [comment]
> The following lines should use relative links instead of hard coded links
> 
> * Introduction to vectors - Lines 24-25
> * Vector magnitudes - Lines 24-26
> * Vector arithmetic - Lines 24-26
> * Collision detection using vectors - Lines 24-28

Thanks for the heads up! These have been updated and will be pushed with in an update shortly.

**Comment by ShaunR1991** [comment]
> Good work on the tutorial, it is very informative. I followed it as the intended "as-you-go" style through the deploy preview, functionally all links and interactive parts of the tutorial work as intended. All code examples were tested and outputted the expected results (C++ & C#). Knowledge and explanations of the topics and their possible use cases were clearly shown and easy to follow. By the end of the tutorial a user would see the benefit and have the knowledge to implement this into their own projects. I feel as though adding code snippets for the functions in '_3-vector-geometry-angles_' , similar to that in the other topics, would be beneficial to the reader. As well as implementing C# code to '_4-collision-detection-using-vectors_'.

I've gone through and added highlighted sections within the code blocks for each of the diagrams to highlight exactly where the functions being used are in the code. I've also added code snippets into part 3. 

I'm still working on getting the C# implementation for part 4 (and soon part 5). This may require adjusting the C++ code to ensure that I can keep the C# code in top level statements. This is on the backlog and not being ignored.

Appreciate the feedback! Will push these changes up in an update shortly.

**Review by omckeon — APPROVED** [review]
These are the most comprehensive tutorials I've seen in Thoth Tech. Incredible work!

I really like the Conclusion sections as well. (I've already mentioned how great the rest is in meetings haha)

**Pull request merged**
