### PR TITLE
Dead/ wrong redirecting links fixed

### PR DESCRIPTION
**Pull request by kay-kaushik**
### Description ###
I manually went through the entire splashkit.io website to find links which resulted in a **404 page not found** error and also I also analyzed links which redirected to wrong pages.  The links have been fixed except links in developer documentation as the mdx generating script needs to be changed. 

### Changes ###
I made changes to all the files necessary. The next section has documented links that resulted in errors. 

### Documentation ###
The documentation for the links that have been found and fixed can be found in this notion website: [https://gratis-chef-9b5.notion.site/Dead-wrong-redirection-Links-Splashkit-website-53913d4a84e74f3cbf592e7c67c3a662](url)

### Testing ###
I tested all the changes made to the code on my machine before creating the pull request. 

### Benefits ###
Fixed links will create better user experience as the user will be able to access information more seamlessly. This increase the user friendliness of the splashkit.io website. 

### Conclusion ###
**This pull request addresses broken and misdirected links on the splashkit.io website, ensuring a smoother user experience. By systematically identifying and fixing these issues, the website's usability and reliability are significantly enhanced.**

### CODE REVIEW

**Comment by kay-kaushik** [comment]
[Find and fix dead links on ported website](https://trello.com/c/X9NG63dc/429-find-and-fix-dead-links-on-ported-website)

**Comment by omckeon** [comment]
Hi @kay-kaushik,
It seems you have accidentally added the usage examples to this PR. To fix this, create a new branch for each PR, and then update those branches with the correct files for those PRs, then update the PR in the web view by clicking "Edit" near the top right part of the page and change the branch that the PR is being made from.

**Comment by kay-kaushik** [comment]
Hi @omckeon, I have edited the branch to only include the dead links commit. Please review it again. Thank you.

**Review by omckeon — APPROVED** [review]
Tested and working nicely with the broken links on the installation, troubleshooting and guide pages all working correctly now.

**Pull request merged**
