### PR TITLE
Point at origin

### PR DESCRIPTION
**Pull request by Jinx-means-jinx**
# Overview
Add usage example point at origin to show how to create a origin point.

Splashkit Function: `point_at_origin`
image
image

# Files Included
- [x] Title and explanation (.txt)
- [x] C++ code
- [x] C# code (top-level statements)
- [x] C# code (Object-Oriented Programming)
- [x] Python code
- [x] Screenshot

# Usage Example Checks
- [x] Simple, clear demonstration of the function
- [x] Code uses Splashkit functions
- [x] Tested in Chrome and Firefox

### CODE REVIEW

**Comment by Jinx-means-jinx** [comment]
fixed

**Review by SimonRhook — APPROVED** [review]
With the changes made as recommended I can now approve this PR. It does a good job of showing a basic use case for the point_at_origin function 

- [x] All required files are present.
  - [x] Title and explanation (.txt)
  - [x] C++ code
  - [x] C# code (top-level statements)
  - [x] C# code (Object-Oriented Programming)
  - [x] Python code
- [x] Code correctly uses Splashkit functions.
- [x] Code clearly demonstrates the function.
- [x] All versions maintain the same structure and comments.
- [x] C++ code ran correctly.
- [x] C# top level code ran correctly.
- [x] C# OOP code ran correctly.
- [x] Python code ran correctly.

**Review by huyhuynh2319 — APPROVED** [review]
I've reviewed the usage examples. Everything ran without issue.

### **Checks**

- [x]  All required files are present.
- [x]  Title and explanation (.txt)
- [x]  C++ code
- [x]  C# code (top-level statements)
- [x]  C# code (Object-Oriented Programming)
- [x]  Python code

### **Tests done**

- [x]  C++ code ran correctly.
- [x]  C# top level code ran correctly.
- [x]  C# OOP code ran correctly.
- [x]  Python code ran correctly.

**Comment by omckeon** [comment]
@Jinx-means-jinx The description was quite poor. This is an important aspect, so I suggest that you look at the change I made to this description and then update your other PRs to improve the descriptions.

**Review by omckeon — APPROVED** [review]

**Pull request merged**
