### PR TITLE
Tutorials on SplashKit's interface functionality

### PR DESCRIPTION
**Pull request by WhyPenguins**
### Overview
This PR adds three new tutorials to the website, focused around the new interface functionality:
 - Getting Started Creating User Interfaces
 - Layouts in User Interfaces
 - Styling User Interfaces

### Testing
It has been viewed locally to ensure it appears correctly and that links and images work, on both Firefox and Edge. The code included in each tutorial has also been tested - this is how the images in each tutorial were generated.

### Note
Does this website have any specific lint/formatting tools that should be ran for new content? Currently I'm just pushing it as I wrote it, but if they exist I'd be happy to run this through them.

### CODE REVIEW

**Comment by WhyPenguins** [comment]
[Write tutorial on SplashKit Interface functionality](https://trello.com/c/cofItCNI/563-write-tutorial-on-splashkit-interface-functionality)

**Comment by edwinshibu** [comment]
The Tutorials look really good.

**Review by Liquidscroll — APPROVED** [review]
Awesome work! These tutorials are clear and easy to follow and the images throughout give a really good impression of what you can do with this. Tbh it actually made me want to go try it out.

**Review by omckeon — APPROVED** [review]

**Comment by omckeon** [comment]
Will wait to merge this till I check the best process for this with Andrew. But great work!

**Comment by WhyPenguins** [comment]
Have made an upstream [PR](https://github.com/splashkit/splashkit.io-starlight/pull/9) so will close this now, thanks everyone! 😄

**Pull request closed without merging**
