### PR TITLE
Fill triangle on bitmap

### PR DESCRIPTION
**Pull request by sharvani28**
The following code shows an example of using the fill_triangle_on_bitmap function to draw a red triangle on a loaded bitmap.

Here is the screenshot of how the Graphics Usage example page looks like:
image

### CODE REVIEW

**Comment by breezy-codes** [comment]
Great work on this usage example and the code files created. I've reviewed the codes and they work correctly. They are in the standard wanted for the splashkit site, using top level statements in C#.
I can't find any errors in any of the files.

## C#
Screenshot from 2024-08-24 09-45-21

## C++
Screenshot from 2024-08-24 09-45-53

## Checked PR in local environment to review site:
Screenshot from 2024-08-24 09-47-52

**Review by breezy-codes — APPROVED** [review]
All files working correctly and free of errors.

**Review by s223126445 — COMMENTED** [review]
Good job both the codes are error free but need space adjustments in the code and the C# follows the top-level statements.
**C#**
C#
**C++**
C++

**Comment by sharvani28** [comment]
Adjusted spaces as per feedback

**Review by s223126445 — APPROVED** [review]
Thank you for the adjustments. Now, the code blocks look good.

**Comment by sharvani28** [comment]
Changed the code as per the feedback.

**Comment by kay-kaushik** [comment]
After thoroughly reviewing the code, I can confirm that it is correct and functions as intended. The image files are located in the appropriate directories, the resources folder works as intended, and the code runs without errors. The implementation aligns with the project requirements, and no further changes are necessary.

Overall, the usage example is well-constructed, and I believe it is ready to be merged into the main branch. Great work! 

image

**Review by omckeon — APPROVED** [review]
Great work making the changes for this function.
It shows up nicely on the page, the Resources links works correctly and the site builds successfully as well.

**Pull request merged**
