### PR TITLE
Fix guides index page

### PR DESCRIPTION
**Pull request by oliverexell-bruce**
# Description

Updated the guides/tutorials index page to restore the cards that were missing and change the filters to sort based on the folder/category they actually relate to.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (update or new)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration.

- [X] Tested in latest Chrome
- [X] Tested in latest Firefox
- [X] npm run build
- [X] npm run preview

### If involving code

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### If modified config files

- [X] I have checked the following files for changes:
  - [X] package.json
  - [X] astro.config.mjs

### CODE REVIEW

**Review by ShaunR1991 — APPROVED** [review]
## Updates to the Guides index page.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [x] Tested in latest Chrome
- [x] Tested in latest Firefox
- [x] npm run build
- [x] npm run preview

## Checklist

### If involving code

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### If modified config files

- [x] I have checked the following files for changes:
  - [x] package.json
  - [x] astro.config.mjs

## Folders and Files Added/Modified

See https://github.com/thoth-tech/splashkit.io-starlight/pull/149/files

PR looks good - future proofs the Guides index by allowing new folders to be added without having to make changes to any other parts of the repo.

**Review by Liquidscroll — APPROVED** [review]
Looks good to me! Tested changes through `npm run dev` and `npm run build` && `npm run preview`.

This will certainly serve as a solid foundation for the automatic indexing of guides and tutorials. The guides overview looks _much_ better without the cards being staggered. Great job!

**Comment by omckeon** [comment]
@oliverexell-bruce I did some testing with this, and removing the card grid made this page even more accessible without needing to scroll so far. As we still have very few tutorials, I think this might be a better solution.
Could you update to remove the CardGrid? Or message me on Teams if you disagree :)

(Eventually it would be great to have the whole list showing on a single page without any scrolling needed, but this is a great first step.)

**Comment by oliverexell-bruce** [comment]
# Description

Updated the guides/tutorials index page to restore the cards that were missing and change the filters to sort based on the folder/category they actually relate to.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (update or new)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration.

- [X] Tested in latest Chrome
- [X] Tested in latest Firefox
- [X] npm run build
- [X] npm run preview

## Checklist

### If involving code

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### If modified config files

- [X] I have checked the following files for changes:
  - [X] package.json
  - [X] astro.config.mjs

**Pull request merged**
