### PR TITLE
Write line integer example

### PR DESCRIPTION
**Pull request by Jinx-means-jinx**
Description
Created a new usage example to show how to use the function "write_line".

Change

- C++ code
- C# code
- Added image to show the output

Code Test
Both C++ and C# code are tested working well

image

### CODE REVIEW

**Review by ShaunR1991 — APPROVED** [review]
Code looks good and executes without error. 

Possible point for discussion is that while you have done a great job of demonstrating how write_line can be used with integers, we should possibly clarify the function's signature and handling of different data types.

Currently, the signature mentioned at the top of the page states void write_line(string line), which implies the function primarily handles strings. While SplashKit does allow you to pass integers directly (as you’ve shown in your examples), it’s important to emphasise that users must be cautious when mixing strings and integers in calculations or concatenations.

For example, if someone were to declare a = "1" (as a string) and then try to add it to an integer, like b = 2 and a + b, they would likely run into errors or unexpected results due to type mismatch. To avoid confusion, I suggest either expanding the signatures section to explicitly state that write_line accepts both integers and strings or we could include an aside or tip warning users about potential issues with type mismatches when performing arithmetic with strings and integers (https://starlight.astro.build/guides/components/)

**Comment by sananoureen35** [comment]
Overall, the implementation is solid. The code demonstrates the write_line function well, showing its ability to print various integers. The examples are very good to follow and cover basic usage cases effectively.

One suggestion from my end would be to include some edge cases, like negative numbers, zero, or large integers, to make the examples more comprehensive. It would also be helpful to clarify how the function handles non-integer values like floats, to avoid confusion for users who might encounter them.

**Review by sananoureen35 — COMMENTED** [review]
Overall, the implementation is solid. The code demonstrates the write_line function well, showing its ability to print various integers. The examples are very good to follow and cover basic usage cases effectively.

One suggestion from my end would be to include some edge cases, like negative or large integers, to make the examples more comprehensive.

**Comment by omckeon** [comment]
@Jinx-means-jinx 
You need to move the files into the `write_line_int` folder, and update the file naming to use `write_line_int-1-print-integer` before the file extension.

**Comment by omckeon** [comment]
@Jinx-means-jinx I have updated the base branch to be using the usage-examples-contributions branch now. Could you update this PR to resolve conflicts?
And make the change in the comment above as well.

**Comment by Jinx-means-jinx** [comment]
> @Jinx-means-jinx You need to move the files into the `write_line_int` folder, and update the file naming to use `write_line_int-1-print-integer` before the file extension.

**Comment by Jinx-means-jinx** [comment]
Change had been made

**Review by sananoureen35 — APPROVED** [review]

**Pull request merged**
