### PR TITLE
Tutorial Review of Mouse Inputs Functionality Guide 

### PR DESCRIPTION
**Pull request by s223126445**
Tutorial Review of Mouse Inputs Functionality Guide

Date Reviewed: 28 August 2024
Reviewed by: Mounika Angadipeta

## Description:

A tutorial review of the tutorial has been done. The code in this tutorial has been run to ensure that it works and outputs the results. The code has all the three languages C++, C#, Python. Modified part of the text description of the sentence and Mouse location Functionality code in C# to make the content clearer.
## Confirmation of Passing Quality Checks:

- [x] The tutorial is free of spelling and grammatical errors.
- [x] The tutorial is easy to follow.
- [x] The tutorial has:
   - [x] C# using top level statements
   - [x] C++
   - [x] Python
- [x] The code passes all the Quality Checks.

Screenshots of Code test run:
**Mouse Button Functionality**
C++
**Mouse Clicked**
Mouse_Clicked
Mouse_Clicked
C#
Mouse_clicked
Mouse-clicked
Python
Mouse_clicked
Mouse-clicked

**Mouse Down**
C++
Mouse_Down
Mouse_Down
C#
Mouse_Down
Mouse_Down
Python
Mouse_down
Mouse_down

**Mouse Up**
C++
Mouse_up
Mouse_up
C#
Mouse_up
Mouse_up
Python
Mouse_up
Mouse_up

**Mouse Movement Functionality**

**Mouse Movements**
C++
Mouse_Movements
Mouse_Movemnets
C#
Mouse_movements
Mouse_Movements
Python
Mouse_Movements
Mouse-Movement

**Mouse Wheel Scroll**
C++
Mouse_wheel_scroll
Mouse_wheel_scroll
C#
Mouse_wheel_scroll
Mouse-wheel-scroll
Python
Mouse_wheel_scroll
Mouse-Scrolling

**Mouse Location Functionality**
**Mouse Position**
C++
Mouse_position
Mouse_Position
C#
Mouse_position
Mouse-position
Python
Mouse_position
Mouse-position

**Mouse Position Vector**
C++
Mouse_position_vector
C#
Mouse-position-vector
Python
Mouse_position_vector

**Mouse x**
C++
Mouse_x
C#
Mouse-x
Python
Mouse_x

**Mouse Y**
C++
Mouse_y
C#
Mouse_y
Python
Mouse_y

**Mouse Visibility**
**Hide/Show Mouse** 
C++
Hide_Show_mouse
C#
Hide-Show-Mouse
Python
Hide_show_mouse

**Show Mouse**
C++
Show_mouse
C#
Show_mouse
Python
Show_mouse

### CODE REVIEW

**Review by Srainyyyy — APPROVED** [review]
Good thorough review. Ensure that all the code can run properly, and the format is neat. The language changes are very good, improving the clarity and structure of the guide and making it easier to understand. Some chapters have been rewritten to eliminate redundancy, while code examples have been updated for consistency. These improvements help users better understand how to implement mouse input with SplashKit, improving the overall quality and usefulness of the tutorial.

**Comment by breezy-codes** [comment]
I've reviewed the program code and all run correctly:

### Python
1mouseclickedpy
2mousedownpy
3mouseuppy
4mousemovepy
5mousewheelpy
6mousepositionpy
7mouseposvectorpy
8mousexpy
9mouseypy
10mousehidepy
11mouseshowpy


### C#
1mouseclickedcs
2mousedowncs
3mouseupcs
4mousemovecs
5mousewheelcs
6mousepositioncs
7mouseposvectorcs
8mousexcs
9mouseycs
10mousehidecs
11mouseshowcs


### C++
1mouseclickedcpp
2mousedowncpp
3mouseupcpp
4mousemovecpp
5mousewheelcpp
6mousepositioncpp
7mouseposvectorcpp
8mousexcpp
9mouseycpp
10mousehidecpp
11mouseshowcpp

**Comment by breezy-codes** [comment]
I've reviewed the deploy preview of the guide and its free of errors and easy to follow.

**Review by breezy-codes — APPROVED** [review]

**Comment by Srainyyyy** [comment]
All the code works properly, the screenshot is as follows:
Mouse Clicked：
c++
image
c#
image

python
image

Mouse Down
c++
image
c#
image

python
image

Mouse Up
c++
image

c#
image

python
image

Mouse Movement
c++
image
image

c#
image
image

python
image
image


Mouse Wheel Scroll
c++
image
image

c#
image
image

python
image
image

Mouse Position
c++
image

c#
image

python
image

Mouse Position Vector
c++
image

c#
image

python
image

Mouse X
c++
image

c#
image

python
image

Mouse Y
c++
image

c#
image

python
image

Hide/Show Mouse
c++
image

c#
image

python
image

Show Mouse
c++
image

c#
image

python
image

**Comment by breezy-codes** [comment]
Your latest commit has now completely removed the introduction to JSON, this will need to be fixed.

**Pull request merged**
