### PR TITLE
Option 2 Landing Page with Individual Links To New Splashkit Installation Pages

### PR DESCRIPTION
**Pull request by DerDieDasDeakin**
This option changes the landing page to have links to each individual step, with pages brought over from the Programmer's Guide.

### CODE REVIEW

**Comment by DerDieDasDeakin** [comment]
[Create Installation Landing page](https://trello.com/c/PpLQSMGC/433-create-installation-landing-page)

**Comment by HarshitaShroff** [comment]
The linkcard have been created for each type Raspberry however the linkcard within each pages are not created and gives an error - page not found. 

Raspberry - linkcard all have error 404 page not found 
example: 
image

when click the linkcard 1. getting the Hardware error as below comes up. 
image

Windows: 
Msys2
- pages linked incorrectly 
- Install splashkit SDK load Visual studio code page
- Install Splashkit globally loads the Language specific tools page
- below pages are not linked for higlighted option
image


wsl: #3 to #6 pages not linked
image

macOS: Pages linked incorrectly
- Install Splashkit globally loads the Visual studio code page
- Install Visual Studio code loads the Language specific tools page
- Install Language specific tools page loads the 404 page not found (Error)
image

**Comment by DerDieDasDeakin** [comment]
A quick note for this one, the links will always 404 as the pages being linked to are not included in this PR. This PR is for referencing the design of the landing page or, depending on what happens, to be merged without the new pages if that is what is needed. The different PRs are just for added flexibility due to the amount of changes being made.

**Comment by omckeon** [comment]
Just closing PRs that can't/won't be merged (due to formatting or other issues), this is separate from any capstone grading.

**Pull request closed without merging**
