### PR TITLE
Fill Circle On Screen Usage Example

### PR DESCRIPTION
**Pull request by rmachu**
This is a usage example of the Fill Circle On Window function. It shows adding 3 circles of different colors and placements to mimic traffic lights on a window. 

Splashkit Function: `Fill_Circle_On_Window`

# Files Included
- [x] Title and explanation (.txt)
- [x] C++ code
- [x] C# code (top-level statements)
- [x] C# code (Object-Oriented Programming)
- [x] Python code
- [x] Screenshot

# Usage Example Checks
- [x] Simple, clear demonstration of the function
- [x] Code uses Splashkit functions
- [x] Tested in Chrome and Firefox

### CODE REVIEW

**Review by Jinx-means-jinx — COMMENTED** [review]
Check the code for oop and running with no error
image

Check the code for top level and running with no error
image

Check the code for C++ and running with no error
image

Check the code for python and running with no error
image

**Review by Jinx-means-jinx — APPROVED** [review]
Only the files of fill_circle_on_window should be change, please undo the change in clear_screen

**Review by EthanRin — APPROVED** [review]
I've reviewed this usage example and have tested each implementation of the program across different languages.
The code is well-structured and is consistent throughout each implementations. I approved of this PR.

### Checklist
- [x] Code uses SplashKit function 
- [x] Code demonstrates uses of the function 
- [x] Python code ran as expected.
- [x] C# OOP code ran as expected.
- [x] C# Top Level code ran as expected
- [x] C++ Code ran as expected 

### Files required 
- [x] Python code 
- [x] C# OOP code
- [x] C# Top Level code 
- [x] C++ Code 
- [x] Screenshot of the program running 
- [x] Title and description

**Review by omckeon — APPROVED** [review]
I've made some updates such as the Window variable name and using the "window" variable in the C# OOP code. For any other examples that are related to "On Window", please update these to use a similar style.

**Pull request merged**
